### ISSUE TITLE
Solving for seats

### ISSUE THREAD

**Issue by jsleslie** [jsleslie/Ohare_taxi_demand#22]
- [x] 1. Merge `passengers2018raw.csv` Aircraft type with `L_AIRCRAFT_TYPE.csv` found [here](https://www.transtats.bts.gov/Download_Lookup.asp?Lookup=L_AIRCRAFT_TYPE) for seat counts and airline and origin

- [x] 2. Create a table/dictionary with Manufacturers, Models and Descriptions for step 3

- [x] 3. Merge the Tail-Numbers from the `plane_details.csv` with the Aircraft type from the `passengers2018raw.csv`. Create a column which goes through each row in plane_details and adds a value corresponding to the appropriate aircraft description in the dictionary from step 2.

- [x] 4. Merge with OTP to create master flight arrivals data

- [x] ** Note that Tail-Numbers are not a complete set. For the ~20% of missing values, the average number of seats for the corresponding airline will be used to impute the number of seats.

**Comment by jsleslie** [comment]
added notebook which downloads in `passengers2018raw.csv` for all years. See #24

**Comment by dkruszew** [comment]
Note for point 2: When using plane_names.csv file, merge on `model` only and not on `manufacturer`. `manufacturer` is different for tail numbers.

**Comment by dkruszew** [comment]
Data wrangling file performs all above operations.
